### PR TITLE
Libpitt/104 column

### PR DESCRIPTION
**Pull request by libpitt**
Change log:
1. Add source type column
2. Add tooltip above column name to describe meaning of Last Touch

### CODE REVIEW

**Comment by libpitt** [comment]
https://github.com/hubmapconsortium/data-ingest-board/issues/105

Screen Shot 2023-11-14 at 2 49 37 PM

**Review by maxsibilla — APPROVED** [review]

**Comment by libpitt** [comment]
@maxsibilla @yuanzhou 
If this `source_type` column is not to be added on HM, then add to `NEXT_PUBLIC_EXCLUDE_TABLE_COLUMNS = '["source_type"]' `

If it has a different name on HM, then add `"source_type": {"field": "donor_type", "name": "Donor Type"}` to the object in `NEXT_PUBLIC_TABLE_COLUMNS`

**Comment by maxsibilla** [comment]
@libpitt The source type column will only appear for SenNet as HuBMAP only has human donors

**Comment by yuanzhou** [comment]
Deployment note:
>For Data Ingest Board, remember `NEXT_PUBLIC_EXCLUDE_TABLE_COLUMNS = '["source_type"]'` for the HM config.

**Review by yuanzhou — APPROVED** [review]
The backend ingest-api changes made.

**Pull request merged**
