### PR TITLE
Libpitt/116 columns

### PR DESCRIPTION
**Pull request by libpitt**
Change log:
1. Add new columns `assigned_to_group_name` and `ingest_task`
2. Add `ModalOver` component to handle `ingest_task` that may be too long for tabular display

### CODE REVIEW

**Comment by yuanzhou** [comment]
@libpitt @maxsibilla have you made the corresponding ingest-api updates in SenNet? On the HuBMAP side, once @DerekFurstPitt proceeds with the https://github.com/hubmapconsortium/ingest-api/issues/417, we'll be able to move along.

**Comment by maxsibilla** [comment]
@yuanzhou yes we have deployed the necessary changes to our Ingest API

**Review by maxsibilla — APPROVED** [review]

**Comment by yuanzhou** [comment]
Corresponding PR in HuBMAP for ingest-api support: https://github.com/hubmapconsortium/ingest-api/pull/434

**Review by yuanzhou — APPROVED** [review]
Will test things out on DEV

**Pull request merged**
